test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      number: 10
    rounds:
      - label: queryinvoke
        description: query and invoke benchmark
        txNumber: 1000
        rateControl:
          type: fixed-load
          opts:
            transactionLoad: 2
        workload:
          module: workload/query.js
          arguments:
            assets: 10
            contractId: basic